version: '3.4'
services:
  webapp:
    image: domec-challange
    container_name: domec
    ports:
      - "44311:44311"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:44311;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=admin@123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_HTTPS_PORT=44311
    volumes:
      - ~/.aspnet\https:/https/


volumes:
  domec:

